"""
Generates a combined Markdown document from an ExtractionResponse
and an optional CrawlResponse.
"""

from typing import Optional

from app.schemas.crawl.response import CrawlResponse
from app.schemas.extraction.response import ExtractionResponse


def to_markdown(result: ExtractionResponse, crawl: Optional[CrawlResponse] = None) -> str:
    lines: list[str] = []

    # ── Title ────────────────────────────────────────────────────────────────
    lines += [f"# {result.topic}", ""]
    lines += [f"> Generated by `{result.source}` · Web research by Tavily", ""]

    # ── Story Overview ───────────────────────────────────────────────────────
    lines += ["## Overview", ""]
    lines += [f"**Narrative:** {result.narrative}", ""]
    lines += [f"**Theme:** {result.theme}", ""]
    lines += [f"**Emotional Tone:** {result.emotional_tone}", ""]
    lines += [f"**Setting:** {result.setting}", ""]

    if result.keywords:
        lines += [f"**Keywords:** {', '.join(result.keywords)}", ""]

    if result.content_warnings:
        lines += [f"> ⚠️ **Content Warnings:** {', '.join(result.content_warnings)}", ""]

    # ── Web Context (from crawl) ─────────────────────────────────────────────
    if crawl and crawl.topic_context:
        lines += ["---", "", "## Real-World Context", "", "> *Sourced from the web via Tavily*", ""]
        lines += [crawl.topic_context, ""]

    # ── Similar Works (from crawl) ───────────────────────────────────────────
    if crawl and crawl.similar_works:
        lines += ["### Similar Works", ""]
        for ref in crawl.similar_works:
            lines += [f"- [{ref.title}]({ref.url}) — {ref.snippet}"]
        lines += [""]

    # ── Characters ───────────────────────────────────────────────────────────
    if result.characters:
        lines += ["---", "", "## Characters", ""]
        for c in result.characters:
            lines += [f"### {c.name}", ""]
            lines += [f"- **Role:** {c.role}"]
            lines += [f"- **Description:** {c.description}"]
            if c.traits:
                lines += [f"- **Traits:** {', '.join(c.traits)}"]
            if c.backstory:
                lines += [f"- **Backstory:** {c.backstory}"]

            # Web references for this character
            if crawl:
                char_research = next(
                    (r for r in crawl.character_research if r.name.lower() == c.name.lower()),
                    None,
                )
                if char_research:
                    lines += [f"- **Web Research:** {char_research.summary}"]
                    for ref in char_research.references[:2]:
                        lines += [f"  - [{ref.title}]({ref.url})"]
            lines += [""]

    # ── Character Relationships ──────────────────────────────────────────────
    if result.relationships:
        lines += ["---", "", "## Character Relationships", ""]
        for rel in result.relationships:
            lines += [
                f"### {rel.from_character} ↔ {rel.to_character}",
                "",
                f"- **Relationship:** {rel.relationship}",
                f"- **Dynamic:** {rel.dynamic}",
                "",
            ]

    # ── Plot ─────────────────────────────────────────────────────────────────
    if result.plot:
        lines += ["---", "", "## Plot", ""]
        lines += [result.plot.summary, ""]

        if result.plot.conflict:
            lines += [f"**Conflict:** {result.plot.conflict}", ""]

        if result.plot.points:
            lines += ["### Story Beats", ""]
            for pt in result.plot.points:
                lines += [f"{pt.order}. {pt.description}"]
            lines += [""]

        if result.plot.resolution:
            lines += [f"**Resolution:** {result.plot.resolution}", ""]

    # ── Video Production Notes ───────────────────────────────────────────────
    lines += ["---", "", "## Video Production Notes", ""]
    v = result.video
    lines += [
        f"- **Style:** {v.style}",
        f"- **Lighting:** {v.lighting}",
        f"- **Color Palette:** {', '.join(v.colors)}",
        f"- **Camera Motion:** {', '.join(v.camera_motion)}",
        "",
        "**Scenes:**",
    ]
    for scene in v.scenes:
        lines += [f"- {scene}"]
    lines += [""]

    if v.objects:
        lines += [f"**Key Props/Objects:** {', '.join(v.objects)}", ""]

    if crawl and crawl.visual_references:
        lines += ["**Visual References (Web):**"]
        for ref in crawl.visual_references[:3]:
            lines += [f"- [{ref.title}]({ref.url}) — {ref.snippet}"]
        lines += [""]

    # ── Audio Production Notes ───────────────────────────────────────────────
    lines += ["---", "", "## Audio Production Notes", ""]
    a = result.audio
    lines += [
        f"- **Genre:** {a.genre}",
        f"- **Tempo:** {a.tempo}",
        f"- **Mood:** {a.mood}",
        f"- **Instruments:** {', '.join(a.instruments)}",
    ]
    if a.sound_effects:
        lines += [f"- **Sound Effects:** {', '.join(a.sound_effects)}"]
    lines += [""]

    if crawl and crawl.audio_references:
        lines += ["**Audio References (Web):**"]
        for ref in crawl.audio_references[:3]:
            lines += [f"- [{ref.title}]({ref.url}) — {ref.snippet}"]
        lines += [""]

    # ── Action Keywords ───────────────────────────────────────────────────────
    if result.action_keywords:
        lines += ["---", "", "## Action Keywords", ""]
        for kw in result.action_keywords:
            lines += [f"- {kw}"]
        lines += [""]

    # ── All Sources ──────────────────────────────────────────────────────────
    if crawl and crawl.all_sources:
        lines += ["---", "", "## All Web Sources", ""]
        for ref in crawl.all_sources:
            lines += [f"- [{ref.title}]({ref.url}) `{ref.category}`"]
        lines += [""]

    return "\n".join(lines)
