ERROR_CODE_INTERNAL = "INTERNAL_ERROR"
ERROR_MSG_INTERNAL = "Internal server error"
ERROR_CODE_VALIDATION = "VALIDATION_ERROR"
ERROR_MSG_VALIDATION = "Request validation failed"
ERROR_CODE_ELEVENLABS_NOT_CONFIGURED = "ELEVENLABS_NOT_CONFIGURED"
ERROR_MSG_ELEVENLABS_NOT_CONFIGURED = "ELEVENLABS_API_KEY is not set"
ERROR_CODE_TTS_FAILED = "TTS_FAILED"
ERROR_MSG_TTS_FAILED = "Text-to-speech generation failed"
ERROR_CODE_DATABRICKS_NOT_CONFIGURED = "DATABRICKS_NOT_CONFIGURED"
ERROR_MSG_DATABRICKS_NOT_CONFIGURED = (
    "DATABRICKS_HOST and DATABRICKS_TOKEN must be set for AI Search"
)
ERROR_CODE_VECTOR_SEARCH_NOT_CONFIGURED = "VECTOR_SEARCH_NOT_CONFIGURED"
ERROR_MSG_VECTOR_SEARCH_NOT_CONFIGURED = (
    "DATABRICKS_VECTOR_SEARCH_ENDPOINT and DATABRICKS_VECTOR_SEARCH_INDEX must be set"
)
ERROR_CODE_VECTOR_SEARCH_FAILED = "VECTOR_SEARCH_FAILED"
ERROR_MSG_VECTOR_SEARCH_FAILED = "Databricks AI Search query failed"
ERROR_CODE_SFX_FAILED = "SFX_FAILED"
ERROR_MSG_SFX_FAILED = "Sound effect generation failed"
ERROR_CODE_AUDIOBOOK_FAILED = "AUDIOBOOK_FAILED"
ERROR_MSG_AUDIOBOOK_FAILED = "Audiobook preview render failed"
